[package]
name = "rafka-producer"
version = "0.1.0"
edition = "2021"

[dependencies]
rafka-core = { path = "../core" }
tonic = "0.9"
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.3", features = ["v4"] }
futures = "0.3"
chrono = { version = "0.4", features = ["serde"] }
