apiVersion: v1
kind: ConfigMap
metadata:
  name: rafka-config
  namespace: rafka
data:
  RAFKA_LOG_LEVEL: "info"
  RAFKA_RETENTION_HOURS: "168"  # 7 days
  RAFKA_MAX_MESSAGE_SIZE: "1048576"  # 1MB
  RAFKA_PARTITION_COUNT: "32"
  RAFKA_REPLICATION_FACTOR: "3"
  RAFKA_THREAD_POOL_SIZE: "32" 