apiVersion: v1
kind: ServiceAccount
metadata:
  name: rafka-sa
  namespace: rafka
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rafka-role
  namespace: rafka
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rafka-role-binding
  namespace: rafka
subjects:
- kind: ServiceAccount
  name: rafka-sa
  namespace: rafka
roleRef:
  kind: Role
  name: rafka-role
  apiGroup: rbac.authorization.k8s.io 