apiVersion: v1
kind: Service
metadata:
  name: rafka-broker
  namespace: rafka
  labels:
    app: rafka
    component: broker
spec:
  ports:
  - port: 9092
    name: broker
  - port: 9093
    name: metrics
  clusterIP: None
  selector:
    app: rafka
    component: broker
---
apiVersion: v1
kind: Service
metadata:
  name: rafka-broker-external
  namespace: rafka
spec:
  type: LoadBalancer
  ports:
  - port: 9092
    targetPort: broker
    name: broker
  selector:
    app: rafka
    component: broker 