apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rafka-broker
  namespace: rafka
spec:
  serviceName: rafka-broker
  replicas: 3
  selector:
    matchLabels:
      app: rafka
      component: broker
  template:
    metadata:
      labels:
        app: rafka
        component: broker
    spec:
      containers:
      - name: rafka-broker
        image: rafka:latest
        ports:
        - containerPort: 9092
          name: broker
        - containerPort: 9093
          name: metrics
        env:
        - name: RAFKA_BROKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RAFKA_NODES
          value: "rafka-broker-0.rafka-broker:9092,rafka-broker-1.rafka-broker:9092,rafka-broker-2.rafka-broker:9092"
        volumeMounts:
        - name: data
          mountPath: /var/lib/rafka
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: broker
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: broker
          initialDelaySeconds: 5
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: rafka-storage
      resources:
        requests:
          storage: 10Gi 