apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rafka-storage
provisioner: kubernetes.io/aws-ebs  # Change based on cloud provider
parameters:
  type: gp3
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer 